# see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
- package-ecosystem: maven
  directory: "/"
  target-branch: "dev"
  schedule:
    interval: daily
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: org.springframework.security.oauth:spring-security-oauth2
  - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
    versions: ["2022.x", "2023.x"]
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions: ["2022.x", "2023.x"]
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions: ["3.x"]
